### ISSUE TITLE
qloar 학습

### ISSUE THREAD

**Issue by taemin6697** [tabtoyou/KoLLaVA#1]
qlora를 통해 학습되는 코드는 언제쯤 공개되는지 알 수 있을까요??
프로젝트를 하는데 써볼까 합니다

**Comment by tabtoyou** [comment]
우선 관심 가져주셔서 감사합니다!
현재 본업이 조금 바빠 시간 할애를 많이 못하고 있네요🥲 혹시 급하시면 [LLaVA Github](https://github.com/haotian-liu/LLaVA)의 LoRA 코드를 참고하시면 좋을 것 같습니다!

**Comment by tabtoyou** [comment]
qlora 학습 코드를 공개했습니다! 보시고 궁금한 점 있으면 이슈 남겨주세요

**Comment by taemin6697** [comment]
결국 제가 만든 모델을 쓰실줄은 상상도 못했네요 ㅋㅋ

**Comment by tabtoyou** [comment]
Llama-2-ko-7b-Chat🦙 모델 공유해주신 분이군요! 좋은 모델 공유해주셔서 감사합니다ㅎㅎ
