### ISSUE TITLE
When is KoLLaVA-Instruct-612k released?

### ISSUE THREAD

**Issue by jsg921019** [tabtoyou/KoLLaVA#14]
First thank you for the great project.
I have been using the translated 150k instruct dataset and noticed you've recently used 612k instruct dataset with is not open yet.
Is there any plan for this dataset to open?

**Comment by tabtoyou** [comment]
Thank you for your interest in the project. 

After a bit of filtering, we have released the 🤗 [KoLLaVA-Instruct-581k](https://huggingface.co/datasets/tabtoyou/KoLLaVA-v1.5-Instruct-581k) dataset on Hugging Face.

I hope this dataset proves helpful to you.
