### ISSUE TITLE
EKVQA 데이터셋 다운로드 및 경로설정에 관해 질문이 있습니다.

### ISSUE THREAD

**Issue by Bleking** [tabtoyou/KoLLaVA#23]
안녕하세요. 모델을 훈련시키기 위해 요구하신 데이터셋들을 다운받던 중 EKVQA 경로에 관한 설명이 부족한듯 하여 질문드립니다.

├── coco
│   └── train2017
├── gqa
│   └── images
├── vg
│   ├── VG_100K
│   └── VG_100K_2
└── ekvqa

구성이 이렇게 되어있고, AIHUB 페이지에 들어가보면 훈련용 및 검증용 데이터셋들이 있습니다. 저는 일단 훈련용 데이터의 '한국적 이미지'와 'TL_LABEL_KB'만 다운받았습니다만, 혹시 '그 외 이미지'와 'TL_LABEL_VQA' 또한 다운받아야 하는 것인지 궁금합니다. 그리고 "ekvqa" 경로 내부에는 그냥 전부 이미지 데이터로 체워지도록 하는 것인지가 궁금합니다.

감사합니다.

**Comment by tabtoyou** [comment]
안녕하세요, 설명이 부족했던 부분을 짚어주셔서 감사합니다ㅎㅎ

> '그 외 이미지'와 'TL_LABEL_VQA' 또한 다운받아야 하는 것인지 궁금합니다.

-> LABEL 데이터는 필요없으며, `한국적 이미지`와 `그 외 이미지` 모두 다운 받으시면 됩니다.

<img width="400" alt="image" src="https://github.com/tabtoyou/KoLLaVA/assets/42518610/a1982191-7921-47ea-9c9d-04fa83eb6bd3">


       
> "ekvqa" 경로 내부에는 그냥 전부 이미지 데이터로 체워지도록 하는 것인지가 궁금합니다.

-> 네 맞습니다. 위에서 다운받은 모든 이미지 데이터를 ekvqa 디렉토리에 옮기시면 됩니다.

**Comment by Bleking** [comment]
감사합니다. 그럼 validation은 필요없이 train 데이터만 모두 받으면 되는건가요?

**Comment by Bleking** [comment]
Validation 없이 진행해보니 데이터가 없다는 에러가 뜨네요. 전부 다 받아야 하는게 맞군요.
감사합니다!
