### ISSUE TITLE
ekvqa 데이터셋 중 존재하지 않는 이미지가 있는 듯 합니다.

### ISSUE THREAD

**Issue by Bleking** [tabtoyou/KoLLaVA#25]
ekvqa 데이터셋의 132303520220926102106.jpg 파일이 없어 학습 진행이 잘 되고 있지 않다는 것입니다.
FileNotFoundError: [Errno 2] No such file or directory: '/home/work/testdataset1/KoLLaVA/workspace/data/ekvqa/132303520220926102106.jpg'

https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=&topMenu=&aihubDataSe=data&dataSetSn=71357
그래서 위의 링크에서 로컬로 다운받고, AI hub API 통해서 받고 압축 풀기 시도를 여러번 해봤는데도, 132303520220926102106.jpg 파일은 전혀 찾을 수 없었습니다.

일단 AI hub에도 해당 이미지가 부재한 것 같다고 문의는 드려놨지만, 현재로서는 어떻게 진행할지 막막하여 다시한번 질문글 남깁니다.

**Comment by tabtoyou** [comment]
json 파일에서 해당 sample을 삭제하시면 이미지 파일이 없어도 학습이 가능합니다.

~~학습에 사용한 ekvqa 이미지 zip 파일도 공유드리겠습니다.~~
