### ISSUE TITLE
상업적 사용이 가능할까요?

### ISSUE THREAD

**Issue by changheecho** [tabtoyou/KoLLaVA#28]
안녕하세요.

한글이 가능한 LLM이 거의 전무한 상황에서 이렇게 좋은 모델을 공개해 주셔서 감사합니다.
혹시 공개하신 KoLLaVA 모델을 사용하여 상용 제품 개발이 가능한지 문의 드립니다.

감사합니다.

**Comment by tabtoyou** [comment]
안녕하세요, KoLLaVA 모델에 관심 가져주셔서 감사합니다.

학습에 사용된 모델 및 데이터를 고려했을 때, 상업적 사용은 제한되며 현재는 연구용으로만 사용 가능합니다.

**Comment by changheecho** [comment]
아 그렇군요. 답변 감사합니다.
