### ISSUE TITLE
KoLLaVA-KULLM-13B-8bit 모델이 사라졌습니다.

### ISSUE THREAD

**Issue by Tococo838** [tabtoyou/KoLLaVA#3]
KoLLaVA-KULLM-13B-8bit 모델이 허깅페이스에서 사라졌습니다.
https://huggingface.co/tabtoyou/KoLLaVA-KULLM-13B-8bit

**Comment by tabtoyou** [comment]
해당 모델의 성능이 만족스럽지 않아 업데이트 중입니다!
곧 qlora 학습 방법 등을 공유할 예정이니 조금만 기다려주세요😊
