### ISSUE TITLE
KeywordsStoppingCriteria import 경로 수정 문의

### ISSUE THREAD

**Issue by hou27** [tabtoyou/KoLLaVA#5]
우선 소중한 정보 공유해주셔서 감사합니다.

<hr>

현재 예제를 보면

```python
from llava.model.utils import KeywordsStoppingCriteria
```
위와 같이 되어있습니다.

그러나 KeywordsStoppingCriteria는 [llava/mm_utils.py#L51](https://github.com/tabtoyou/KoLLaVA/blob/72e9491536c9729ad193b4e19cdc67ae9b520e51/llava/mm_utils.py#L51)에 있어 아래와 같이 수정한 후 진행했습니다!

```python
from llava.mm_utils import KeywordsStoppingCriteria
```

맞는 정보라면 수정해주실 수 있을까요?

**Comment by tabtoyou** [comment]
좋은 피드백 감사합니다.

말씀하신대로 
```python
from llava.model.utils import KeywordsStoppingCriteria
```

부분은 LLaMA-2 버전으로 업데이트 하기 전 코드인데요.

LLaMA-2 버전으로 업데이트 하며 수정된 코드가 꽤 있어, 
말씀해주신 부분 외에도 추가로 수정할 부분이 많이 있습니다.

이러한 부분을 반영하기 전에 우선 [Colab](https://github.com/tabtoyou/KoLLaVA/blob/main/KoLLaVA-Kovicuna-7b_inference_test.ipynb
)에서 [tabtoyou/KoLLaVA-KoVicuna-7b](https://huggingface.co/tabtoyou/KoLLaVA-KoVicuna-7b) 모델이 잘 작동하도록 
이전 commit 을 불러와 실행하는 코드로 수정했습니다.


제가 놓치고 있던 부분인데 이렇게 피드백 주셔서 감사합니다.
빠른 시일 내에 LLaMA-2 버전도 Colab에서 실행되는 코드를 공유하겠습니다.

**Comment by hou27** [comment]
답변 감사합니다.

LLaMA-2 버전으로 넘어가면서 바뀐 부분이었군요
설명 감사합니다 ㅎㅎ
