### ISSUE TITLE
Build LLaVA v1.5

### ISSUE THREAD

**Issue by Mineru98** [tabtoyou/KoLLaVA#6]
Are you planning to develop a new version?

I want to contribute together

**Comment by tabtoyou** [comment]
First of all, thank you for showing interest in the project. 

Yes, I have plans to update it to version 1.5. It should be possible by the end of October. 

Feel free to go ahead and work on it, and you can submit a pull request (PR) when you're ready. If you'd like to coordinate or have any questions, you can also reach out to me at [gxq9106@gmail.com](mailto:gxq9106@gmail.com).
