### ISSUE TITLE
Plan for adding KoScienceQA dataset for instruct tuning?

### ISSUE THREAD

**Issue by treasuraid** [tabtoyou/KoLLaVA#7]
First, thank you for great work on KoLLAVA. 

how about adding KoScienceQA dataset for instruct tuning? The performance would be competitive or not?

**Comment by tabtoyou** [comment]
Thank you for your interest in KoLLaVA. 

I have been exploring various evaluation methods for the model.
However, I don't have immediate plans to translate and test the ScienceQA dataset in Korean.

If its original meaning remains intact through translation, testing it could be a good direction 👍
