### ISSUE TITLE
안녕하세요. qlora finetune 이후, pytorch.bin 파일이 생성이 되지 않아 질문 남깁니다..!

### ISSUE THREAD

**Issue by SOSONAGI** [tabtoyou/KoLLaVA#8]
우선 좋은 자료를 공유해 주셔서 감사 드립니다.

덕분에 저희 연구에 많은 도움이 되고 있습니다. 감사합니다.

다름이 아니오라, 첨부의 사진과 같이 학습이후, qlora로 학습된 파일은 생성이 되었는데  bin 파일이 없어 여쭙니다..

혹시 convert 등 작업을 별도로 해야하는건가요..?

참고로 학습 시, 하이퍼파라미터 등은 안내해 주신 수치 그대로 진행하였습니다..!

![1](https://github.com/tabtoyou/KoLLaVA/assets/103930629/f355ed68-9f77-401a-8366-b14fcc6c3648)
![2](https://github.com/tabtoyou/KoLLaVA/assets/103930629/95680f9b-7654-4e8b-8ee8-de63012ba88e)
![3](https://github.com/tabtoyou/KoLLaVA/assets/103930629/5c322164-fe1b-4684-a28c-5b4f20d63896)

답변 주시면 감사하겠습니다..!

**Comment by tabtoyou** [comment]
안녕하세요, 답변이 늦어져 죄송합니다

프로젝트에 관심가져주셔 감사합니다.

qlora로 학습할 경우 기존 base 모델은 freeze 하고, adapter 부분만 학습합니다.
즉, 변하지 않는 base 모델의 파라미터는 이미 저장되어 있기 때문에 adapter 부분의 파라미터만 저장됩니다.

보내주신 이미지에서도 adapter_model.bin에 adapter의 파라미터가 저장된 걸 알 수 있습니다.

사용하실 때 각각 따로 불러와서 사용할 수 있지만 base와 adapter 파라미터를 하나로 합치고 싶으시다면,
KoLLaVA/scripts/merge_lora_weights.py 를 참고하시면 될 것 같습니다
(
https://github.com/tabtoyou/KoLLaVA/blob/2f962e9600573fbdbd4725d844d78295d82d4c10/scripts/merge_lora_weights.py#L6
)

혹시 해결이 안 된다면 얘기해주세요!
감사합니다.



2023년 10월 18일 (수) 오후 3:03, SUN YOUNG HWANG ***@***.***>님이 작성:

**Comment by SOSONAGI** [comment]
답변 감사합니다 :)
